//This c++ code is generated by PictoBlox

//Included Libraries
#include <Servo.h>

//MACROS are defined here
Servo Servo3;

void setup() {
	//put your setup code here, to run once:
	Servo3.attach(3);
	pinMode(5, INPUT);
	pinMode(7, OUTPUT);
	pinMode(8, INPUT);
	
	
	Servo3.write(110);
}

void loop() {
	//put your main code here, to run repeatedly:
	
	
	if(digitalRead(5)) {
		digitalWrite(7, true);
		if((!(digitalRead(8)))) {
			Servo3.write(0);
			delay(2 * 1000);
		}
		else {
			Servo3.write(110);
			delay(2 * 1000);
		}
	}
	else {
		digitalWrite(7, false);
	}
}
